baseURL = "http://mermeu.github.io/"
languageCode = "nl-nl"
defaultContentLanguage = "nl"
publishDir = "../mermeu.github.io"
title = "Logboek van mijn Proces"
theme = "whiteplain"
[params]
showShareIcons = false
dateFormat = "2 January 2006"
[[menu.main]]
    name = "Portfolio"
    weight = 20
    url = "/portfolio/" 
[[menu.main]]
    name = "Blog"
    weight = 10
    url = "/posts/"

[[menu.footer]]
name = "!! De vormgeving van dit blog is nog steeds in ontwikkeling !!" 
