baseURL = "http://example.org/"
languageCode = "nl-nl"
defaultContentLanguage = "nl"
publishDir = "../mermeu.github.io"
title = "Merijns 2e site"
theme = "whiteplain"
[[menu.main]]
    name = "Portfolio"
    weight = 20
    url = "/portfolio/" 
[[menu.main]]
    name = "Blog"
    weight = 10
    url = "/posts/"

[[menu.footer]]
name = "De vormgeving van dit blog is nog steeds in ontwikkeling" 
